import { useLocale } from "../i18n";

const copy = {
  imageWorking: ["Creating presentation images", "正在生成演示配图"],
  runtimeWorking: ["Building your presentation", "正在制作演示文稿"],
  elapsed: ["Elapsed", "已用时"],
  lastUpdate: ["Last activity", "最近进展"],
  justNow: ["Just now", "刚刚"],
  secondsAgo: ["s ago", " 秒前"],
  minutesAgo: ["m ago", " 分钟前"],
  delayed: ["No new progress for a while", "暂未收到新的进展"],
  delayedHint: ["The provider may still be processing. Check task status before starting another run.", "服务可能仍在处理中，可以先刷新状态确认进展。"],
  statusUnavailable: ["Status check unavailable", "状态查询暂不可用"],
  refresh: ["Refresh status", "刷新任务状态"],
  refreshed: ["Status checked", "已检查任务状态"],
  previewPending: ["Your presentation is taking shape", "你的演示文稿正在成形"],
  outlineNext: ["Story structure", "梳理内容"],
  designNext: ["Layout & images", "排版配图"],
  readyNext: ["Review & edit", "预览编辑"],
  queued: ["Queued", "排队中"],
  generating: ["Writing content", "正在生成正文"],
  repairing: ["Retrying this page", "正在重试本页"],
  ready: ["Content ready", "正文已完成"],
  failed: ["Page failed", "本页生成失败"],
  canceled: ["Stopped", "已停止"],
  skipResearch: ["Skip research and continue", "跳过研究，继续生成"],
  contentReady: ["Page content ready", "正文已完成"],
  viewContent: ["View content", "查看正文"],
  stillProcessing: ["The runtime is responding and still waiting for the service. Completed content will appear below.", "任务仍在响应，正在等待服务返回。已完成内容会在下方展示。"],

  request: ["Your request", "你的需求"],
  outline: ["Shape the story", "先把故事讲清楚"],
  outlineReady: ["Outline ready", "大纲已生成"],
  direction: ["Visual direction", "让故事有自己的表达"],
  directionAuto: ["Layouts and images follow your brief and the generated visual plan.", "版式与配图将依据你的需求和生成的视觉方案展开。"],
  directionPending: ["The visual direction will appear when it is available.", "视觉方案准备好后会在这里展示。"],
  directionReady: ["Visual direction prepared", "视觉方向已准备"],
  generate: ["Your ideas are taking shape", "你的想法，正在逐页成形"],
  waiting: ["Waiting for your confirmation", "等待你确认"],
  preparing: ["Preparing the next page", "正在准备下一页"],
  contentPreview: ["Content preview · open the editor for the final layout", "内容预览 · 最终排版请查看编辑器"],
  contentPending: ["Page content is being prepared", "正在整理页面内容"],
  follow: ["Follow latest", "跟随最新内容"],
  following: ["Following latest", "正在跟随最新内容"],
  details: ["Generation details", "生成详情"],
  debug: ["Debug: replay from zero", "Debug：从零演示"],
  exitDebug: ["Return to live task", "返回真实任务"],
  demo: ["Simulated preview · your live task is unchanged", "模拟演示 · 不影响真实任务"],
  demoDone: ["Demo complete", "演示完成"],
  demoBrief: ["Create a brand launch presentation covering the product story, benefits and launch plan.", "做一份品牌新品发布 PPT，介绍产品故事、核心优势和上市计划。"],
  demoTitle: ["Make room for possibility", "让日常，多一种可能"],
  demoOne: ["Start with real needs", "从真实需求出发"],
  demoTwo: ["Three reasons to choose us", "三个值得选择的理由"],
  demoThree: ["Design for every day", "让好设计融入每一天"],
  demoFour: ["Bring the product to people", "把新品带到用户身边"],
  demoFive: ["Start something new together", "一起开启新的可能"],
  minimal: ["Minimal", "极简留白"],
  dark: ["Warm contrast", "暖色对比"],
  natural: ["Natural texture", "自然质感"],
  styleDemo: ["Recommended visual styles", "正在推荐视觉风格"],
  moveUp: ["Move section up", "上移这一部分"],
  moveDown: ["Move section down", "下移这一部分"],
} as const;
export function usePptxFlowCopy() {
  const locale = useLocale();
  return (key: keyof typeof copy) => copy[key][locale === "zh" ? 1 : 0];
}
