/** Generated from typed source semantics. Status: candidate; not an exact-verified solution. */
export const sourceSlide = 133;
export const gaps = [];
export async function build(PowerPoint) {
  if (gaps.some(g => g.blocking)) throw new Error("JSSDK capability gaps: " + JSON.stringify(gaps));
  await PowerPoint.run(async context => {
    const count = context.presentation.slides.getCount();
    await context.sync();
    if (count.value !== 0) throw new Error("Requires an empty presentation");
    context.presentation.pageSetup.slideWidth = 960;
    context.presentation.pageSetup.slideHeight = 540;
    context.presentation.slides.add();
    await context.sync();
    const slide = context.presentation.slides.getItemAt(0);
    slide.background.fill.setSolidFill({color: "#FFFFFF"});
    // slide-133-object-1: 文本框 1
    const s1 = slide.shapes.addTextBox("", {"left":155.72094488188975,"top":117.40850393700788,"width":670.6046456692914,"height":60.58590551181102});
    s1.name = "文本框 1";
    s1.fill.clear();
    s1.lineFormat.visible = false;
    s1.textFrame.textRange.text = "Contents";
    s1.textFrame.leftMargin = 7.2;
    s1.textFrame.rightMargin = 7.2;
    s1.textFrame.topMargin = 3.6;
    s1.textFrame.bottomMargin = 3.6;
    s1.textFrame.verticalAlignment = "Middle";
    s1.textFrame.wordWrap = true;
    s1.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s1.textFrame.textRange.paragraphFormat.horizontalAlignment = "Center";
    s1.textFrame.textRange.font.size = 44;
    s1.textFrame.textRange.font.name = "Arial";
    s1.textFrame.textRange.font.eastAsianName = "+mn-ea";
    s1.textFrame.textRange.font.language = "en-US";
    s1.textFrame.textRange.font.bold = true;
    s1.textFrame.textRange.font.italic = false;
    s1.textFrame.textRange.font.spacing = 0;
    s1.textFrame.textRange.font.color = "#04918B";
    // slide-133-object-2: 椭圆 11
    const s2 = slide.shapes.addGeometricShape("Ellipse", {"left":641.9855905511811,"top":279.39417322834646,"width":41.714330708661414,"height":41.714330708661414});
    s2.name = "椭圆 11";
    s2.fill.setSolidColor("#4472C4");
    s2.lineFormat.weight = 1;
    s2.lineFormat.capStyle = "Flat";
    s2.lineFormat.alignment = "Center";
    s2.lineFormat.style = "Single";
    s2.lineFormat.dashStyle = "Solid";
    s2.lineFormat.joinStyle = "Miter";
    s2.lineFormat.miterLimit = 8;
    s2.lineFormat.visible = false;
    s2.textFrame.textRange.text = "";
    s2.textFrame.leftMargin = 7.2;
    s2.textFrame.rightMargin = 7.2;
    s2.textFrame.topMargin = 3.6;
    s2.textFrame.bottomMargin = 3.6;
    s2.textFrame.verticalAlignment = "Middle";
    s2.textFrame.wordWrap = true;
    s2.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s2.textFrame.textRange.paragraphFormat.horizontalAlignment = "Center";
    // slide-133-object-3: 文本框 15
    const s3 = slide.shapes.addTextBox("", {"left":690.3970866141732,"top":278.4958267716535,"width":191.3779527559055,"height":43.853228346456696});
    s3.name = "文本框 15";
    s3.hiddenFill = {"kind":"solid","color":{"value":"FFFFFF","colorKind":"srgb"}};
    s3.hiddenLine = {"fill":{"kind":"solid","color":{"value":"000000","colorKind":"srgb"}},"join":{"kind":"miter","miterLimit":800000},"headEnd":{},"tailEnd":{},"lineWidth":9525};
    s3.fill.clear();
    s3.lineFormat.visible = false;
    s3.textFrame.textRange.text = "LOREM IPSUM ";
    s3.textFrame.leftMargin = 7.2;
    s3.textFrame.rightMargin = 7.2;
    s3.textFrame.topMargin = 3.6;
    s3.textFrame.bottomMargin = 3.6;
    s3.textFrame.verticalAlignment = "Middle";
    s3.textFrame.wordWrap = true;
    s3.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s3.textFrame.textRange.paragraphFormat.horizontalAlignment = "Left";
    s3.textFrame.textRange.paragraphFormat.fontAlignment = "Baseline";
    s3.textFrame.textRange.paragraphFormat.spaceBeforeMultiple = 0;
    s3.textFrame.textRange.paragraphFormat.spaceAfterMultiple = 0;
    s3.textFrame.textRange.font.size = 20;
    s3.textFrame.textRange.font.name = "Arial";
    s3.textFrame.textRange.font.eastAsianName = "+mn-ea";
    s3.textFrame.textRange.font.language = "en-US";
    s3.textFrame.textRange.font.bold = false;
    s3.textFrame.textRange.font.italic = false;
    s3.textFrame.textRange.font.spacing = 0;
    s3.textFrame.textRange.font.color = "#808080";
    // slide-133-object-4: 椭圆 5
    const s4 = slide.shapes.addGeometricShape("Ellipse", {"left":360.1051968503937,"top":279.3942519685039,"width":41.714330708661414,"height":41.714330708661414});
    s4.name = "椭圆 5";
    s4.fill.setSolidColor("#E2268F");
    s4.lineFormat.weight = 1;
    s4.lineFormat.capStyle = "Flat";
    s4.lineFormat.alignment = "Center";
    s4.lineFormat.style = "Single";
    s4.lineFormat.dashStyle = "Solid";
    s4.lineFormat.joinStyle = "Miter";
    s4.lineFormat.miterLimit = 8;
    s4.lineFormat.visible = false;
    s4.textFrame.textRange.text = "";
    s4.textFrame.leftMargin = 7.2;
    s4.textFrame.rightMargin = 7.2;
    s4.textFrame.topMargin = 3.6;
    s4.textFrame.bottomMargin = 3.6;
    s4.textFrame.verticalAlignment = "Middle";
    s4.textFrame.wordWrap = true;
    s4.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s4.textFrame.textRange.paragraphFormat.horizontalAlignment = "Center";
    // slide-133-object-5: 文本框 16
    const s5 = slide.shapes.addTextBox("", {"left":408.51669291338584,"top":278.49590551181103,"width":191.3779527559055,"height":43.853228346456696});
    s5.name = "文本框 16";
    s5.hiddenFill = {"kind":"solid","color":{"value":"FFFFFF","colorKind":"srgb"}};
    s5.hiddenLine = {"fill":{"kind":"solid","color":{"value":"000000","colorKind":"srgb"}},"join":{"kind":"miter","miterLimit":800000},"headEnd":{},"tailEnd":{},"lineWidth":9525};
    s5.fill.clear();
    s5.lineFormat.visible = false;
    s5.textFrame.textRange.text = "LOREM IPSUM ";
    s5.textFrame.leftMargin = 7.2;
    s5.textFrame.rightMargin = 7.2;
    s5.textFrame.topMargin = 3.6;
    s5.textFrame.bottomMargin = 3.6;
    s5.textFrame.verticalAlignment = "Middle";
    s5.textFrame.wordWrap = true;
    s5.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s5.textFrame.textRange.paragraphFormat.horizontalAlignment = "Left";
    s5.textFrame.textRange.paragraphFormat.fontAlignment = "Baseline";
    s5.textFrame.textRange.paragraphFormat.spaceBeforeMultiple = 0;
    s5.textFrame.textRange.paragraphFormat.spaceAfterMultiple = 0;
    s5.textFrame.textRange.font.size = 20;
    s5.textFrame.textRange.font.name = "Arial";
    s5.textFrame.textRange.font.eastAsianName = "+mn-ea";
    s5.textFrame.textRange.font.language = "en-US";
    s5.textFrame.textRange.font.bold = false;
    s5.textFrame.textRange.font.italic = false;
    s5.textFrame.textRange.font.spacing = 0;
    s5.textFrame.textRange.font.color = "#808080";
    // slide-133-object-6: 椭圆 3
    const s6 = slide.shapes.addGeometricShape("Ellipse", {"left":78.22488188976378,"top":279.3944094488189,"width":41.714330708661414,"height":41.714330708661414});
    s6.name = "椭圆 3";
    s6.fill.setSolidColor("#04918B");
    s6.lineFormat.weight = 1;
    s6.lineFormat.capStyle = "Flat";
    s6.lineFormat.alignment = "Center";
    s6.lineFormat.style = "Single";
    s6.lineFormat.dashStyle = "Solid";
    s6.lineFormat.joinStyle = "Miter";
    s6.lineFormat.miterLimit = 8;
    s6.lineFormat.visible = false;
    s6.textFrame.textRange.text = "";
    s6.textFrame.leftMargin = 7.2;
    s6.textFrame.rightMargin = 7.2;
    s6.textFrame.topMargin = 3.6;
    s6.textFrame.bottomMargin = 3.6;
    s6.textFrame.verticalAlignment = "Middle";
    s6.textFrame.wordWrap = true;
    s6.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s6.textFrame.textRange.paragraphFormat.horizontalAlignment = "Center";
    // slide-133-object-7: 文本框 19
    const s7 = slide.shapes.addTextBox("", {"left":126.63637795275591,"top":278.496062992126,"width":191.3779527559055,"height":43.853228346456696});
    s7.name = "文本框 19";
    s7.hiddenFill = {"kind":"solid","color":{"value":"FFFFFF","colorKind":"srgb"}};
    s7.hiddenLine = {"fill":{"kind":"solid","color":{"value":"000000","colorKind":"srgb"}},"join":{"kind":"miter","miterLimit":800000},"headEnd":{},"tailEnd":{},"lineWidth":9525};
    s7.fill.clear();
    s7.lineFormat.visible = false;
    s7.textFrame.textRange.text = "LOREM IPSUM ";
    s7.textFrame.leftMargin = 7.2;
    s7.textFrame.rightMargin = 7.2;
    s7.textFrame.topMargin = 3.6;
    s7.textFrame.bottomMargin = 3.6;
    s7.textFrame.verticalAlignment = "Middle";
    s7.textFrame.wordWrap = true;
    s7.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s7.textFrame.textRange.paragraphFormat.horizontalAlignment = "Left";
    s7.textFrame.textRange.paragraphFormat.fontAlignment = "Baseline";
    s7.textFrame.textRange.paragraphFormat.spaceBeforeMultiple = 0;
    s7.textFrame.textRange.paragraphFormat.spaceAfterMultiple = 0;
    s7.textFrame.textRange.font.size = 20;
    s7.textFrame.textRange.font.name = "Arial";
    s7.textFrame.textRange.font.eastAsianName = "+mn-ea";
    s7.textFrame.textRange.font.language = "en-US";
    s7.textFrame.textRange.font.bold = false;
    s7.textFrame.textRange.font.italic = false;
    s7.textFrame.textRange.font.spacing = 0;
    s7.textFrame.textRange.font.color = "#808080";
    await context.sync();
  });
}
