/** Generated from typed source semantics. Status: candidate; not an exact-verified solution. */
export const sourceSlide = 330;
export const gaps = [{"objectId":"slide-330-object-3","feature":"text.inheritedFont","detail":"No explicit font in run or paragraph defaults; inheriting theme font 苹方-简","blocking":false,"owner":"jssdk-shape-compiler","direction":"mop-to-jssdk"},{"objectId":"slide-330-object-7","feature":"text.inheritedFont","detail":"No explicit font in run or paragraph defaults; inheriting theme font 苹方-简","blocking":false,"owner":"jssdk-shape-compiler","direction":"mop-to-jssdk"},{"objectId":"slide-330-object-11","feature":"text.inheritedFont","detail":"No explicit font in run or paragraph defaults; inheriting theme font 苹方-简","blocking":false,"owner":"jssdk-shape-compiler","direction":"mop-to-jssdk"}];
export async function build(PowerPoint) {
  if (gaps.some(g => g.blocking)) throw new Error("JSSDK capability gaps: " + JSON.stringify(gaps));
  await PowerPoint.run(async context => {
    const count = context.presentation.slides.getCount();
    await context.sync();
    if (count.value !== 0) throw new Error("Requires an empty presentation");
    context.presentation.pageSetup.slideWidth = 960;
    context.presentation.pageSetup.slideHeight = 540;
    context.presentation.slides.add();
    await context.sync();
    const slide = context.presentation.slides.getItemAt(0);
    slide.background.fill.setSolidFill({color: "#FFFFFF"});
    // slide-330-object-1: 矩形 27
    const s1 = slide.shapes.addGeometricShape("Rectangle", {"left":353.07149606299214,"top":104.33551181102362,"width":60.927795275590555,"height":72.53307086614173});
    s1.name = "矩形 27";
    s1.rotation = 14.7565;
    s1.fill.clear();
    s1.lineFormat.weight = 1.5;
    s1.lineFormat.color = "#C8E9FF";
    s1.textFrame.textRange.text = "";
    s1.textFrame.leftMargin = 7.2;
    s1.textFrame.rightMargin = 7.2;
    s1.textFrame.topMargin = 3.6;
    s1.textFrame.bottomMargin = 3.6;
    s1.textFrame.verticalAlignment = "Middle";
    s1.textFrame.wordWrap = true;
    s1.textFrame.verticalText = "horz";
    s1.textFrame.columnCount = 1;
    s1.textFrame.columnSpacing = 0;
    s1.textFrame.compatibleLineSpacing = true;
    s1.textFrame.forceAntialias = false;
    s1.textFrame.fromWordArt = false;
    s1.textFrame.horizontalOverflow = "overflow";
    s1.textFrame.verticalOverflow = "overflow";
    s1.textFrame.firstLastParagraphSpacing = false;
    s1.textFrame.bodyRotation = 0;
    s1.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s1.textFrame.textRange.paragraphFormat.horizontalAlignment = "Justify";
    s1.textFrame.textRange.paragraphFormat.lineSpacingMultiple = 1.3;
    // slide-330-object-2: 矩形 28
    const s2 = slide.shapes.addGeometricShape("Rectangle", {"left":352.80070866141733,"top":104.46417322834645,"width":60.927795275590555,"height":72.53307086614173});
    s2.name = "矩形 28";
    s2.fill.setSolidColor("#5ABCFE");
    s2.lineFormat.visible = false;
    s2.textFrame.textRange.text = "";
    s2.textFrame.leftMargin = 0;
    s2.textFrame.rightMargin = 0;
    s2.textFrame.topMargin = 0;
    s2.textFrame.bottomMargin = 0;
    s2.textFrame.verticalAlignment = "Middle";
    s2.textFrame.wordWrap = true;
    s2.textFrame.verticalText = "horz";
    s2.textFrame.columnCount = 1;
    s2.textFrame.columnSpacing = 0;
    s2.textFrame.compatibleLineSpacing = true;
    s2.textFrame.forceAntialias = false;
    s2.textFrame.fromWordArt = false;
    s2.textFrame.horizontalOverflow = "overflow";
    s2.textFrame.verticalOverflow = "overflow";
    s2.textFrame.firstLastParagraphSpacing = false;
    s2.textFrame.bodyRotation = 0;
    s2.textFrame.autoSizeSetting = "AutoSizeNone";
    s2.textFrame.textRange.paragraphFormat.horizontalAlignment = "Center";
    s2.textFrame.textRange.paragraphFormat.lineSpacingMultiple = 1.3;
    // slide-330-object-3: 文本框 25
    const s3 = slide.shapes.addTextBox("", {"left":360.352125984252,"top":120.06724409448819,"width":46.09582677165354,"height":41.198425196850394});
    s3.name = "文本框 25";
    s3.fill.clear();
    s3.lineFormat.visible = false;
    s3.textFrame.textRange.text = "01";
    s3.textFrame.leftMargin = 7.2;
    s3.textFrame.rightMargin = 7.2;
    s3.textFrame.topMargin = 3.6;
    s3.textFrame.bottomMargin = 3.6;
    s3.textFrame.verticalAlignment = "Top";
    s3.textFrame.wordWrap = false;
    s3.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s3.textFrame.textRange.paragraphFormat.horizontalAlignment = "Left";
    s3.textFrame.textRange.font.size = 28;
    s3.textFrame.textRange.font.name = "苹方-简";
    s3.textFrame.textRange.font.language = "en-US";
    s3.textFrame.textRange.font.bold = true;
    s3.textFrame.textRange.font.italic = false;
    s3.textFrame.textRange.font.spacing = 0;
    s3.textFrame.textRange.font.color = "#FFFFFF";
    // slide-330-object-4: 矩形 1
    const s4 = slide.shapes.addGeometricShape("Rectangle", {"left":424.0555118110236,"top":100.7303937007874,"width":183.14377952755905,"height":80.00062992125984});
    s4.name = "矩形 1";
    s4.blackWhiteMode = "auto";
    s4.hiddenFill = {"kind":"solid","color":{"value":"FFFFFF","colorKind":"srgb"}};
    s4.hiddenLine = {"fill":{"kind":"solid","color":{"value":"000000","colorKind":"srgb"}},"join":{"kind":"miter","miterLimit":800000},"headEnd":{},"tailEnd":{},"lineWidth":9525};
    s4.shapeLocks = {"noChangeArrowheads":true};
    s4.fill.clear();
    s4.lineFormat.visible = false;
    s4.textFrame.textRange.text = "单击此处添加文本具体内容";
    s4.textFrame.leftMargin = 7.2;
    s4.textFrame.rightMargin = 7.2;
    s4.textFrame.topMargin = 3.6;
    s4.textFrame.bottomMargin = 3.6;
    s4.textFrame.verticalAlignment = "Middle";
    s4.textFrame.wordWrap = true;
    s4.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s4.textFrame.textRange.paragraphFormat.horizontalAlignment = "Left";
    s4.textFrame.textRange.paragraphFormat.lineSpacingMultiple = 1.2;
    s4.textFrame.textRange.font.size = 14;
    s4.textFrame.textRange.font.name = "Arial";
    s4.textFrame.textRange.font.eastAsianName = "微软雅黑";
    s4.textFrame.textRange.font.language = "zh-CN";
    s4.textFrame.textRange.font.bold = false;
    s4.textFrame.textRange.font.italic = false;
    s4.textFrame.textRange.font.spacing = 1.5;
    s4.textFrame.textRange.font.color = "#5F5F5F";
    // slide-330-object-5: 矩形 33
    const s5 = slide.shapes.addGeometricShape("Rectangle", {"left":353.07149606299214,"top":233.6048031496063,"width":60.927795275590555,"height":72.53307086614173});
    s5.name = "矩形 33";
    s5.rotation = 14.7565;
    s5.fill.clear();
    s5.lineFormat.weight = 1.5;
    s5.lineFormat.color = "#C8E9FF";
    s5.textFrame.textRange.text = "";
    s5.textFrame.leftMargin = 7.2;
    s5.textFrame.rightMargin = 7.2;
    s5.textFrame.topMargin = 3.6;
    s5.textFrame.bottomMargin = 3.6;
    s5.textFrame.verticalAlignment = "Middle";
    s5.textFrame.wordWrap = true;
    s5.textFrame.verticalText = "horz";
    s5.textFrame.columnCount = 1;
    s5.textFrame.columnSpacing = 0;
    s5.textFrame.compatibleLineSpacing = true;
    s5.textFrame.forceAntialias = false;
    s5.textFrame.fromWordArt = false;
    s5.textFrame.horizontalOverflow = "overflow";
    s5.textFrame.verticalOverflow = "overflow";
    s5.textFrame.firstLastParagraphSpacing = false;
    s5.textFrame.bodyRotation = 0;
    s5.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s5.textFrame.textRange.paragraphFormat.horizontalAlignment = "Justify";
    s5.textFrame.textRange.paragraphFormat.lineSpacingMultiple = 1.3;
    // slide-330-object-6: 矩形 34
    const s6 = slide.shapes.addGeometricShape("Rectangle", {"left":352.80070866141733,"top":233.73346456692914,"width":60.927795275590555,"height":72.53307086614173});
    s6.name = "矩形 34";
    s6.fill.setSolidColor("#7CD6E9");
    s6.lineFormat.visible = false;
    s6.textFrame.textRange.text = "";
    s6.textFrame.leftMargin = 0;
    s6.textFrame.rightMargin = 0;
    s6.textFrame.topMargin = 0;
    s6.textFrame.bottomMargin = 0;
    s6.textFrame.verticalAlignment = "Middle";
    s6.textFrame.wordWrap = true;
    s6.textFrame.verticalText = "horz";
    s6.textFrame.columnCount = 1;
    s6.textFrame.columnSpacing = 0;
    s6.textFrame.compatibleLineSpacing = true;
    s6.textFrame.forceAntialias = false;
    s6.textFrame.fromWordArt = false;
    s6.textFrame.horizontalOverflow = "overflow";
    s6.textFrame.verticalOverflow = "overflow";
    s6.textFrame.firstLastParagraphSpacing = false;
    s6.textFrame.bodyRotation = 0;
    s6.textFrame.autoSizeSetting = "AutoSizeNone";
    s6.textFrame.textRange.paragraphFormat.horizontalAlignment = "Center";
    s6.textFrame.textRange.paragraphFormat.lineSpacingMultiple = 1.3;
    // slide-330-object-7: 文本框 31
    const s7 = slide.shapes.addTextBox("", {"left":360.352125984252,"top":249.33653543307088,"width":46.09582677165354,"height":41.198425196850394});
    s7.name = "文本框 31";
    s7.fill.clear();
    s7.lineFormat.visible = false;
    s7.textFrame.textRange.text = "02";
    s7.textFrame.leftMargin = 7.2;
    s7.textFrame.rightMargin = 7.2;
    s7.textFrame.topMargin = 3.6;
    s7.textFrame.bottomMargin = 3.6;
    s7.textFrame.verticalAlignment = "Top";
    s7.textFrame.wordWrap = false;
    s7.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s7.textFrame.textRange.paragraphFormat.horizontalAlignment = "Left";
    s7.textFrame.textRange.font.size = 28;
    s7.textFrame.textRange.font.name = "苹方-简";
    s7.textFrame.textRange.font.language = "en-US";
    s7.textFrame.textRange.font.bold = true;
    s7.textFrame.textRange.font.italic = false;
    s7.textFrame.textRange.font.spacing = 0;
    s7.textFrame.textRange.font.color = "#FFFFFF";
    // slide-330-object-8: 矩形 1
    const s8 = slide.shapes.addGeometricShape("Rectangle", {"left":424.0555118110236,"top":229.9996850393701,"width":183.14377952755905,"height":80.00062992125984});
    s8.name = "矩形 1";
    s8.blackWhiteMode = "auto";
    s8.hiddenFill = {"kind":"solid","color":{"value":"FFFFFF","colorKind":"srgb"}};
    s8.hiddenLine = {"fill":{"kind":"solid","color":{"value":"000000","colorKind":"srgb"}},"join":{"kind":"miter","miterLimit":800000},"headEnd":{},"tailEnd":{},"lineWidth":9525};
    s8.shapeLocks = {"noChangeArrowheads":true};
    s8.fill.clear();
    s8.lineFormat.visible = false;
    s8.textFrame.textRange.text = "单击此处添加文本具体内容";
    s8.textFrame.leftMargin = 7.2;
    s8.textFrame.rightMargin = 7.2;
    s8.textFrame.topMargin = 3.6;
    s8.textFrame.bottomMargin = 3.6;
    s8.textFrame.verticalAlignment = "Middle";
    s8.textFrame.wordWrap = true;
    s8.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s8.textFrame.textRange.paragraphFormat.horizontalAlignment = "Left";
    s8.textFrame.textRange.paragraphFormat.lineSpacingMultiple = 1.2;
    s8.textFrame.textRange.font.size = 14;
    s8.textFrame.textRange.font.name = "Arial";
    s8.textFrame.textRange.font.eastAsianName = "微软雅黑";
    s8.textFrame.textRange.font.language = "zh-CN";
    s8.textFrame.textRange.font.bold = false;
    s8.textFrame.textRange.font.italic = false;
    s8.textFrame.textRange.font.spacing = 1.5;
    s8.textFrame.textRange.font.color = "#5F5F5F";
    // slide-330-object-9: 矩形 39
    const s9 = slide.shapes.addGeometricShape("Rectangle", {"left":353.07149606299214,"top":362.874094488189,"width":60.927795275590555,"height":72.53307086614173});
    s9.name = "矩形 39";
    s9.rotation = 14.7565;
    s9.fill.clear();
    s9.lineFormat.weight = 1.5;
    s9.lineFormat.color = "#C8E9FF";
    s9.textFrame.textRange.text = "";
    s9.textFrame.leftMargin = 7.2;
    s9.textFrame.rightMargin = 7.2;
    s9.textFrame.topMargin = 3.6;
    s9.textFrame.bottomMargin = 3.6;
    s9.textFrame.verticalAlignment = "Middle";
    s9.textFrame.wordWrap = true;
    s9.textFrame.verticalText = "horz";
    s9.textFrame.columnCount = 1;
    s9.textFrame.columnSpacing = 0;
    s9.textFrame.compatibleLineSpacing = true;
    s9.textFrame.forceAntialias = false;
    s9.textFrame.fromWordArt = false;
    s9.textFrame.horizontalOverflow = "overflow";
    s9.textFrame.verticalOverflow = "overflow";
    s9.textFrame.firstLastParagraphSpacing = false;
    s9.textFrame.bodyRotation = 0;
    s9.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s9.textFrame.textRange.paragraphFormat.horizontalAlignment = "Justify";
    s9.textFrame.textRange.paragraphFormat.lineSpacingMultiple = 1.3;
    // slide-330-object-10: 矩形 40
    const s10 = slide.shapes.addGeometricShape("Rectangle", {"left":352.80070866141733,"top":363.00275590551183,"width":60.927795275590555,"height":72.53307086614173});
    s10.name = "矩形 40";
    s10.fill.setSolidColor("#5DD4FF");
    s10.lineFormat.visible = false;
    s10.textFrame.textRange.text = "";
    s10.textFrame.leftMargin = 0;
    s10.textFrame.rightMargin = 0;
    s10.textFrame.topMargin = 0;
    s10.textFrame.bottomMargin = 0;
    s10.textFrame.verticalAlignment = "Middle";
    s10.textFrame.wordWrap = true;
    s10.textFrame.verticalText = "horz";
    s10.textFrame.columnCount = 1;
    s10.textFrame.columnSpacing = 0;
    s10.textFrame.compatibleLineSpacing = true;
    s10.textFrame.forceAntialias = false;
    s10.textFrame.fromWordArt = false;
    s10.textFrame.horizontalOverflow = "overflow";
    s10.textFrame.verticalOverflow = "overflow";
    s10.textFrame.firstLastParagraphSpacing = false;
    s10.textFrame.bodyRotation = 0;
    s10.textFrame.autoSizeSetting = "AutoSizeNone";
    s10.textFrame.textRange.paragraphFormat.horizontalAlignment = "Center";
    s10.textFrame.textRange.paragraphFormat.lineSpacingMultiple = 1.3;
    // slide-330-object-11: 文本框 37
    const s11 = slide.shapes.addTextBox("", {"left":360.352125984252,"top":378.60582677165354,"width":46.09582677165354,"height":41.198425196850394});
    s11.name = "文本框 37";
    s11.fill.clear();
    s11.lineFormat.visible = false;
    s11.textFrame.textRange.text = "03";
    s11.textFrame.leftMargin = 7.2;
    s11.textFrame.rightMargin = 7.2;
    s11.textFrame.topMargin = 3.6;
    s11.textFrame.bottomMargin = 3.6;
    s11.textFrame.verticalAlignment = "Top";
    s11.textFrame.wordWrap = false;
    s11.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s11.textFrame.textRange.paragraphFormat.horizontalAlignment = "Left";
    s11.textFrame.textRange.font.size = 28;
    s11.textFrame.textRange.font.name = "苹方-简";
    s11.textFrame.textRange.font.language = "en-US";
    s11.textFrame.textRange.font.bold = true;
    s11.textFrame.textRange.font.italic = false;
    s11.textFrame.textRange.font.spacing = 0;
    s11.textFrame.textRange.font.color = "#FFFFFF";
    // slide-330-object-12: 矩形 1
    const s12 = slide.shapes.addGeometricShape("Rectangle", {"left":424.0555118110236,"top":359.26897637795275,"width":183.14377952755905,"height":80.00062992125984});
    s12.name = "矩形 1";
    s12.blackWhiteMode = "auto";
    s12.hiddenFill = {"kind":"solid","color":{"value":"FFFFFF","colorKind":"srgb"}};
    s12.hiddenLine = {"fill":{"kind":"solid","color":{"value":"000000","colorKind":"srgb"}},"join":{"kind":"miter","miterLimit":800000},"headEnd":{},"tailEnd":{},"lineWidth":9525};
    s12.shapeLocks = {"noChangeArrowheads":true};
    s12.fill.clear();
    s12.lineFormat.visible = false;
    s12.textFrame.textRange.text = "单击此处添加文本具体内容";
    s12.textFrame.leftMargin = 7.2;
    s12.textFrame.rightMargin = 7.2;
    s12.textFrame.topMargin = 3.6;
    s12.textFrame.bottomMargin = 3.6;
    s12.textFrame.verticalAlignment = "Middle";
    s12.textFrame.wordWrap = true;
    s12.textFrame.autoSizeSetting = "AutoSizeTextToFitShape";
    s12.textFrame.textRange.paragraphFormat.horizontalAlignment = "Left";
    s12.textFrame.textRange.paragraphFormat.lineSpacingMultiple = 1.2;
    s12.textFrame.textRange.font.size = 14;
    s12.textFrame.textRange.font.name = "Arial";
    s12.textFrame.textRange.font.eastAsianName = "微软雅黑";
    s12.textFrame.textRange.font.language = "zh-CN";
    s12.textFrame.textRange.font.bold = false;
    s12.textFrame.textRange.font.italic = false;
    s12.textFrame.textRange.font.spacing = 1.5;
    s12.textFrame.textRange.font.color = "#5F5F5F";
    await context.sync();
  });
}
